apiVersion: ships.k8s.io/v1beta1
kind: Sloop
metadata:
  name: sloop-sample
  annotations:
spec:
  # Add fields here
  foo: bar

  cpu: "2"
  memory: "500M"

  size: 2
  image: nginx:1.7.9
  ports:
    - name: server
      port: 80
      targetPort: 80
      protocol: TCP

      #nodePort: 30002

