
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ships.k8s.io
  resources:
  - sloops
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ships.k8s.io
  resources:
  - sloops/status
  verbs:
  - get
  - patch
  - update
